title: Prof. Jacson Rodrigues Correia-Silva
email: jacson.silva@ufes.br
description: >-
  Site dedicado ao aprendizado e ao compartilhamento do conhecimento com os demais.
baseurl: ""
url: "https://www.jeiks.net"
twitter_username: jeiks
github_username:  jeiks
avatar: imgs/avatar.jpg

twitter_url: https://twitter.com/jeiks
#facebook_url:
#googleplus_url:
#instagram_url:
linkedin_url: https://www.linkedin.com/in/jacson-correia-silva
github_url: https://github.com/jeiks
#stackoverflow_url:
#pinterest_url:
#slack_url:
#dribbble_url:

# Build settings
#theme: minima
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
#plugins:
#  - jekyll-feed
